### ISSUE TITLE
Subjectlist should not be required for publish

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-press#347]
When trying to publish col11740 US History I got the below error. It is caused by the `subjectlist` field being missing from collection.xml file. Press should not throw an error and should allow publishing even if the `subjectlist` is missing or empty.

## Neb output
```
status: 500
  contents: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
Traceback (most recent call last):
  File "/usr/local/bin/neb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/_common.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/publish.py", line 228, in publish
    has_published = _publish(base_url, struct, message, username, password)
  File "/usr/local/lib/python3.6/site-packages/nebu/cli/publish.py", line 198, in _publish
    raise RuntimeError('unknown response, see output above')
RuntimeError: unknown response, see output above
```

## cnx-press traceback
```
  File "/var/cnx/apps/press/press/views/legacy_publishing.py", line 74, in publish
    db_conn)
  File "/var/cnx/apps/press/press/legacy_publishing/litezip.py", line 75, in publish_litezip
    modules_changed=modules_changed)
  File "/var/cnx/apps/press/press/legacy_publishing/collection.py", line 93, in publish_legacy_book
    elif needs_minor_rev(pre, post_tree):
  File "/var/cnx/apps/press/press/legacy_publishing/utils.py", line 54, in needs_minor_rev
    if pre.find('subjectlist').alltext() != post.find('subjectlist').alltext():
AttributeError: 'NoneType' object has no attribute 'alltext'
```

**Comment by BryanEliDimas** [comment]
@Bkblodget I've created a fix for this: https://github.com/openstax/cnx-press/pull/348

**Comment by BryanEliDimas** [comment]
The PR has been merged. Should we add this to a release?

**Comment by omehes** [comment]
verified on various books without subjectlist (col11740, col24361). fixed

neb 9.0.1
